### ISSUE TITLE
bcgraph-export RPC connection failure

### ISSUE THREAD

**Issue by Voelundr** [behas/bitcoingraph#11]
I got this error message:
> Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bitcoingraph-0.3.2.dev0-py3.5.egg/bitcoingraph/bitcoingraph.py", line 53, in __get_blockchain
  File "/usr/local/lib/python3.5/dist-packages/bitcoingraph-0.3.2.dev0-py3.5.egg/bitcoingraph/bitcoind.py", line 178, in getinfo
  File "/usr/local/lib/python3.5/dist-packages/bitcoingraph-0.3.2.dev0-py3.5.egg/bitcoingraph/bitcoind.py", line 48, in call
  File "/usr/local/lib/python3.5/dist-packages/bitcoingraph-0.3.2.dev0-py3.5.egg/bitcoingraph/bitcoind.py", line 92, in _execute
bitcoingraph.bitcoind.BitcoindException: RPC connection failure: 404 Not Found
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
  File "/usr/local/bin/bcgraph-export", line 4, in <module>
    __import__('pkg_resources').run_script('bitcoingraph==0.3.2.dev0', 'bcgraph-export')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/bitcoingraph-0.3.2.dev0-py3.5.egg/EGG-INFO/scripts/bcgraph-export", line 41, in <module>
  File "/usr/local/lib/python3.5/dist-packages/bitcoingraph-0.3.2.dev0-py3.5.egg/bitcoingraph/bitcoingraph.py", line 40, in __init__
  File "/usr/local/lib/python3.5/dist-packages/bitcoingraph-0.3.2.dev0-py3.5.egg/bitcoingraph/bitcoingraph.py", line 58, in __get_blockchain
bitcoingraph.bitcoingraph.BitcoingraphException: Couldn't connect to localhost.

Bitcoind is running and i can excecute successfully:
`curl --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getrawtransaction", "params": ["110ed92f558a1e3a94976ddea5c32f030670b5c58c3cc4d857ac14d7a1547a90", 1] }' -H 'content-type: text/plain;' http://your_rpcuser:your_rpcpass@localhost:8332/`
and
`http://localhost:8332/rest/block/000000000000000e7ad69c72afc00dc4e05fc15ae3061c47d3591d07c09f2928.json`

**Comment by Voelundr** [comment]
Same for Python 3.4
> Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/bitcoingraph-0.3.2.dev0-py3.4.egg/bitcoingraph/bitcoingraph.py", line 53, in __get_blockchain
  File "/usr/local/lib/python3.4/site-packages/bitcoingraph-0.3.2.dev0-py3.4.egg/bitcoingraph/bitcoind.py", line 178, in getinfo
  File "/usr/local/lib/python3.4/site-packages/bitcoingraph-0.3.2.dev0-py3.4.egg/bitcoingraph/bitcoind.py", line 48, in call
  File "/usr/local/lib/python3.4/site-packages/bitcoingraph-0.3.2.dev0-py3.4.egg/bitcoingraph/bitcoind.py", line 92, in _execute
bitcoingraph.bitcoind.BitcoindException: RPC connection failure: 404 Not Found
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
  File "/usr/local/bin/bcgraph-export", line 4, in <module>
    __import__('pkg_resources').run_script('bitcoingraph==0.3.2.dev0', 'bcgraph-export')
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1505, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.4/site-packages/bitcoingraph-0.3.2.dev0-py3.4.egg/EGG-INFO/scripts/bcgraph-export", line 41, in <module>
  File "/usr/local/lib/python3.4/site-packages/bitcoingraph-0.3.2.dev0-py3.4.egg/bitcoingraph/bitcoingraph.py", line 40, in __init__
  File "/usr/local/lib/python3.4/site-packages/bitcoingraph-0.3.2.dev0-py3.4.egg/bitcoingraph/bitcoingraph.py", line 58, in __get_blockchain
bitcoingraph.bitcoingraph.BitcoingraphException: Couldn't connect to localhost.

**Comment by Voelundr** [comment]
Found the Error:
In `bitcoingraph/bitcoingraph.py` on line 53 getinfo is called. 
Please note:
> error code: -32601
> error message:
> getinfo
> 
> This call was removed in version 0.16.0. Use the appropriate fields from:
> - getblockchaininfo: blocks, difficulty, chain
> - getnetworkinfo: version, protocolversion, timeoffset, connections, proxy, relayfee, warnings
> - getwalletinfo: balance, keypoololdest, keypoolsize, paytxfee, unlocked_until, walletversion
>
> bitcoin-cli has the option -getinfo to collect and format these in the old format.

So i changed the call for `getinfo` into `getblockcount` and it is working.

**Comment by DavidNagilla** [comment]
Hi Yiwesi, I am facing the same error word by word and changed the getinfo call but couldnt solve the issue, Can you please put in some more details about other changes u might have made which might help.?
Thanks.
