### ISSUE TITLE
Error when exporting the graph

### ISSUE THREAD

**Issue by archienorman11** [behas/bitcoingraph#8]
Any idea on the following error when trying to export the graph? 

```
[File "//anaconda/lib/python3.5/site-packages/bitcoingraph-0.3.2.dev0-py3.5.egg/bitcoingraph/bitcoind.py", line 92, in _execute
bitcoingraph.bitcoind.BitcoindException: RPC connection failure: 405 Method Not Allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda/bin/bcgraph-export", line 4, in <module>
    __import__('pkg_resources').run_script('bitcoingraph==0.3.2.dev0', 'bcgraph-export')
  File "//anaconda/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 719, in run_script
  File "//anaconda/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 1511, in run_script
  File "//anaconda/lib/python3.5/site-packages/bitcoingraph-0.3.2.dev0-py3.5.egg/EGG-INFO/scripts/bcgraph-export", line 41, in <module>
  File "//anaconda/lib/python3.5/site-packages/bitcoingraph-0.3.2.dev0-py3.5.egg/bitcoingraph/bitcoingraph.py", line 40, in __init__
  File "//anaconda/lib/python3.5/site-packages/bitcoingraph-0.3.2.dev0-py3.5.egg/bitcoingraph/bitcoingraph.py", line 58, in __get_blockchain
bitcoingraph.bitcoingraph.BitcoingraphException: Couldn't connect to localhost.
](url)
```

**Comment by romankarl** [comment]
This code is currently not in use and the development was done with Bitcoin Core 11. I've made a quick fix for Bitcoin Core 12 now. You can try the latest version.
